name: Bug Report
description: Report a reproducible bug in openclaw-engram
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this. Please include enough detail to reproduce.
  - type: textarea
    id: summary
    attributes:
      label: What happened?
      description: A clear description of the bug and expected behavior.
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction steps
      description: Minimal, numbered steps.
      placeholder: |
        1. Configure ...
        2. Run ...
        3. Observe ...
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: openclaw-engram version
      placeholder: e.g. 7.2.1
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs/errors
      description: Paste relevant redacted logs.
  - type: checkboxes
    id: safety
    attributes:
      label: Safety checks
      options:
        - label: I removed secrets/tokens from logs and screenshots.
          required: true
